# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'MarvelApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'lottie-ios'
    pod 'ViewAnimator'
    pod 'Firebase/Analytics'
    pod 'Kingfisher', '~> 7.0'

  # Pods for MarvelApp

  target 'MarvelAppTests' do
    inherit! :search_paths
  end

end
